# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e686bbd2778a603d8eda4b4c9c68b222154dd225684fd02748810d80d8b7cf97df8babc48d46e6a197fb339e6b1a165f903becb5022dd765aeeb7ace56e15587

test:
  secret_key_base: b707181d6023a013d1c139f9c0700d65d72802509d561daf798dc72c577857af87027daa36facf9f40b035b85024e23b9b239c58c773a7c3b4c3f39946cdcea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
